# TODO: research  how to make proper hot-reload setup
#! this docker-compose setup is not functional at the moment

services:
  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    entrypoint: ["/bin/bash", "-c", "tr -d '\\r' < /entrypoint.sh > /tmp/entrypoint.sh && chmod +x /tmp/entrypoint.sh && /bin/bash /tmp/entrypoint.sh"]

  backend:
    build: ./backend
    container_name: backend-dev
    ports:
      - "8080:8080"
    depends_on:
      - redis

  llm-server:
    build: ./llm-server
    container_name: llm-server-dev
    depends_on:
      - redis
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama2:13b

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080

volumes:
  ollama_data: 