services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"



  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  # command: serve && pull llama3.1:8b && run llama3.1:8b

  go-api:
    build: ./backend
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - redis

  python-worker:
    build: ./llm-server
    container_name: python-worker
    depends_on:
      - redis
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama2:13b

volumes:
  ollama_data:
